export {
  EXERCISES,
  STORAGE_KEY,
  FIRST_SESSION_KEY,
  MOBILITY_DONE_KEY,
  REST_DURATION,
  DEFAULT_TARGETS_REPS,
  DEFAULT_TARGETS_PLANK,
  TRAINING_DAYS,
  MOBILITY_EXERCISES,
  MICRO_BREAK_EXERCISES,
} from '@traindaily/core';
